### ISSUE TITLE
Loadash vulnerabilities --> Update it to 4.17.11

### ISSUE THREAD

**Issue by orekav** [matrus2/request-ntlm#1]
I am facing an NPM AUDIT alert

Low             Prototype Pollution
  Package         lodash
  Patched in      >=4.17.5
  Dependency of   request-ntlm
  Path            request-ntlm > lodash
  More info       https://nodesecurity.io/advisories/577

Moderate        Prototype Pollution
  Package         lodash
  Patched in      >=4.17.11
  Dependency of   request-ntlm
  Path            request-ntlm > lodash
  More info       https://nodesecurity.io/advisories/782

**Comment by matrus2** [comment]
To install this package do:
`npm install request-ntlm-promise`

This library doesn't use lodash at all.

Closing.

**Comment by orekav** [comment]
It uses it indirectly, have you checked?
