### ISSUE TITLE
Status Code and Response Headers for a successful request

### ISSUE THREAD

**Issue by agliolio** [matrus2/request-ntlm#3]
Hi

How do I get the response status code and response headers of a successful request so that I can make further assertions on them for my tests?

For error scenarios, the error object has a lot more detailed information than for a successful case. 

When I do a successful post request with NTLM, I'm only able to get the response body when everything goes well. 
But when I do a post request and get a non-200 response, I can extract the statusCode.
And in both successful/non-successful cases, I'm not able to see any information on the response headers.

**Comment by matrus2** [comment]
Hi, 
the library fully supports all params passed to `request-promise`, so in your case just add:
`resolveWithFullResponse: true`

**Comment by agliolio** [comment]
Thank for the quick response. that option is perfect!
